package com.example.handispace.navigation

object Routes {
    const val SPLASH = "splash"
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val HOME = "home"
    const val SHOP = "shop"
    const val SEARCH = "search"
    const val PRODUCT_DETAIL = "product_detail/{productId}"
    const val CART = "cart"
    const val CHECKOUT = "checkout"
    const val PROFILE = "profile"
    const val EDIT_PROFILE = "edit_profile"
    const val ADDRESS = "address"
    const val MY_VOUCHER = "my_voucher"
    const val VOUCHER_HISTORY = "voucher_history"
    const val ORDER_HISTORY = "order_history"
    const val ORDER_DETAIL = "order_detail"
    const val LOYALTY_SCREEN = "loyalty_screen"
    const val REVIEW_ORDER = "review_order"
    const val CHAT = "chat/{targetUserId}/{targetUserName}?context={context}"
    const val AI_CHAT = "ai_chat"
    const val ADMIN_DASHBOARD = "admin_dashboard"
    const val ADMIN_PRODUCTS = "admin_products"
    const val ADMIN_ORDERS = "admin_orders"
    const val ADMIN_CHAT = "admin_chat"
    const val ADMIN_ORDER_DETAIL = "admin_order_detail"
    const val ADMIN_USERS = "admin_users"
    const val ADMIN_CATEGORIES = "admin_categories"
    const val ADMIN_ADD_PRODUCT = "admin_add_product"
    const val ADMIN_EDIT_PRODUCT = "admin_edit_product"
    const val ADMIN_ADD_CATEGORY = "admin_add_category"
    const val ADMIN_EDIT_CATEGORY = "admin_edit_category"
    const val ADMIN_USER_DETAIL = "admin_user_detail"
    const val ADMIN_VOUCHERS = "admin_vouchers"
    const val ADMIN_ADD_VOUCHER = "admin_add_voucher"
    const val ADMIN_EDIT_VOUCHER = "admin_edit_voucher"
    const val FORGOT_PASSWORD = "forgot_password"
}